version: '3.7'

services:
  db:
    image: "postgres:latest"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  superlists:
    build: .
    command: python /superlists/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/superlists
    ports:
      - 8000:8000
    depends_on:
      - db
  
volumes:
  postgres_data: