version: '3.9'

services:
  db:
    image: "postgres:latest"
    container_name: db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  superlists:
    build:
      context: .
    command: python /superlists/manage.py runserver 0.0.0.0:8000
    container_name: superlists
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
  
volumes:
  postgres_data:
