# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(default=uuid.uuid4, max_length=40)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(model_name="user", name="id"),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
