# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-03 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lists", "0004_item_list")]

    operations = [
        migrations.AlterUniqueTogether(
            name="item", unique_together=set([("list", "text")])
        )
    ]
