# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-19 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lists", "0008_auto_20210619_1416")]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_with", to=settings.AUTH_USER_MODEL
            ),
        )
    ]
